################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://products.conholdate.com"
title = "All of Aspose and GroupDocs APIs combined in Conholdate.Total suite"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"

################################# Menus ##############################
[params.menu]
en = "conholdate-en"
fr = "conholdate-fr"
zh = "conholdate-zh"
ru = "conholdate-ru"
tr = "conholdate-tr"
pt = "conholdate-pt"
ar = "conholdate-ar"
es = "conholdate-es"
ja = "conholdate-ja"

################################# Localization #########################
# Disabled languages
disableLanguages = []
defaultContentLang = 'en'
[languages]
    [languages.en]
        languageName = "English"
        languageCode = "en"
        contentDir = "content/english"
        flag = "flag-us"
        weight = 1
    [languages.fr]
        languageName = "Français"
        languageCode = "fr"
        contentDir = "content/french"
        flag = "flag-fr"
        weight = 2
    [languages.zh]
        languageName = "中国人"
        languageCode = "zh"
        contentDir = "content/chinese"
        flag = "flag-zh"
        weight = 3
    [languages.ru]
        languageName = "Русский"
        languageCode = "ru"
        contentDir = "content/russian"
        flag = "flag-ru"
        weight = 4
    [languages.tr]
        languageName = "Türkçe"
        languageCode = "tr"
        contentDir = "content/turkish"
        flag = "flag-tr"
        weight = 5
    [languages.pt]
        languageName = "Português"
        languageCode = "pt"
        contentDir = "content/portuguese"
        flag = "flag-pt"
        weight = 6
    [languages.ar]
        languageName = "عربي"
        languageCode = "ar"
        contentDir = "content/arabic"
        flag = "flag-ar"
        weight = 7
    [languages.es]
        languageName = "Español"
        languageCode = "es"
        contentDir = "content/spanish"
        flag = "flag-es"
        weight = 8
    [languages.ja]
        languageName = "日本"
        languageCode = "ja"
        contentDir = "content/japanese"
        flag = "flag-ja"
        weight = 9

################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]

################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

################################# Default parameters ##########################
[params]
logo = "https://cms.admin.containerize.com/templates/conholdate/img/logo.png"
logo_width = "270px"
# OpenGraph / Twitter Card metadata
description = "Enable your applications to manipulate Word, Excel, PDF, PowerPoint, Outlook and more than 100 other file formats for all major platforms."
author = "Conholdate"
# this image will be used as fallback if a page has no image of its own
image = "https://cms.admin.containerize.com/templates/conholdate/img/logo.png"

################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2
        
################################# Deployment #########################
[deployment]

[[deployment.targets]]
name = "Production"
URL = "s3://products.conholdate.com/?region=us-west-2"

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true