################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://products-qa.conholdate.com"
title = "All of Aspose and GroupDocs APIs combined in Conholdate.Total suite"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []

################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]

################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

################################# Default parameters ##########################
[params]
logo = "https://cms.admin.containerize.com/templates/conholdate/img/logo.png"
logo_width = "270px"
# OpenGraph / Twitter Card metadata
description = "Enable your applications to manipulate Word, Excel, PDF, PowerPoint, Outlook and more than 100 other file formats for all major platforms."
author = "Conholdate"
# this image will be used as fallback if a page has no image of its own
image = "https://cms.admin.containerize.com/templates/conholdate/img/logo.png"

################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2

################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

[deployment]

[[deployment.targets]]
name = "Stage"
URL = "s3://products-qa.conholdate.com/?region=us-west-2"

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
#pattern = "^sitemap\\.xml$"
#pattern = "^[a-z]\\.xml$"
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true
